---
##### Play to add private IPs of k8s-master, k8s-node1, k8s-node2 to master.sh and nodes.sh scripts.
- name: Add private IP of k8s instances to init scripts 
  hosts: localhost
  tasks:
    - name: Run add_k8s_ip.sh
      shell: ./add_k8s_ip.sh

##### Play to setup and configure k8s control plane node #####
- name: Setup k8s Control Plane (master) node
  hosts: k8s-master
  become: true
  tasks:
    - name: Copy master.sh script to k8s control plane node
      copy:
        src: master.sh
        dest: /root/master.sh
        mode: '0755'
    - name: Configure Control Plane (master) node
      shell: /root/master.sh
      notify: Hold kubelet, kubeadm, and kubectl at current version
    - name: Get kubeadm join command
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
      changed_when: false
      delegate_to: localhost
      run_once: true
    - name: Create join_cluster to local file
      become: yes
      copy: 
        content: "{{ kubernetes_join_command.stdout }}" 
        dest: ~/kubernetes_join_command 
        owner: ubuntu
        mode: '0644'
      delegate_to: localhost
      run_once: true
    - name: Create kubectl alias
      lineinfile:
        dest: /root/.bashrc
        line: 'alias k=kubectl'
        state: present
- handlers:
  - name: Hold kubelet, kubeadm, and kubectl at current version
    apt:
      name: "{{ item }}"
      state: hold
    loop:
    - kubelet
    - kubeadm
    - kubectl

##### Play to configure kubectl for ubuntu user #####
- name: Configure kubectl for ubuntu user
  hosts: k8s-master
  become: true
  tasks:
    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: Copy admin.conf to ubuntu's .kube directory
      copy:
        remote_src: "true"
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Set environment variable for kubectl for Ubuntu user 
      lineinfile:
        dest: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'
        state: present
        create: yes
      notify:
        - Reload bashrc
- handlers: 
  - name: Reload bashrc
    shell: 'source /home/ubuntu/.bashrc'
    args:
      executable: /bin/bash

##### Play to setup and configure k8s worker node1 #####
- name: Setup k8s worker node
  hosts: k8s-node1
  become: true
  tasks:
    - name: Copy nodes.sh script to k8s worker node
      copy:
        src: nodes.sh
        dest: /root/nodes.sh
        mode: '0755'
    - name: Configure Worker node
      shell: /root/nodes.sh
    - name: Copy kubernetes_join_command
      copy:
        src: ~/kubernetes_join_command
        dest: /root/kubernetes_join_command
        mode: '0755'
    - name: Join k8s cluster  
      shell: /root/kubernetes_join_command
      when: kubernetes_join_command is defined

##### Play to setup and configure k8s worker node2 #####
- name: Setup k8s worker node
  hosts: k8s-node2
  become: true
  tasks:
    - name: Copy nodes.sh script to k8s worker node
      copy:
        src: nodes.sh
        dest: /root/nodes.sh
        mode: '0755'
    - name: Configure Worker node
      shell: /root/nodes.sh
    - name: Copy kubernetes_join_command
      copy:
        src: ~/kubernetes_join_command
        dest: /root/kubernetes_join_command
        mode: '0755'
    - name: Join k8s cluster  
      shell: /root/kubernetes_join_command
      when: kubernetes_join_command is defined

#### Plays to copy kubeconfig to jenkins server for jenkins user #### Required for Stage V & VI : Deploying application on k8s cluster #####

##### PLAY 1 : COPY kubeconfig from k8s-master node to localhost #####
- name: Copy the kubeconfig from k8s-master 
  hosts: k8s-master
  become: true
  tasks:
  - name: Fetch the file from the k8s-master to localhost
    run_once: yes
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: "./{{ inventory_hostname }}/admin.conf"
      flat: yes
    delegate_to: k8s-master
  - name: Copy the kubeconfig to the worker nodes
      copy:
        src: "./{{ inventory_hostname }}/admin.conf"
        dest: "/home/ubuntu/.kube/config"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      when: inventory_hostname != 'k8s-master'

##### PLAY 2 : INSTALL KUBECTL, CREATE .kube direcoty in $HOME of jenkins user, copy kubeconfig from localhost buffer to Jenkins server and sets the permission to 0600 and ownership to jenkins:jenkins#####
- name: Jenkins User kubectl Setup
  hosts: jenkins
  become: true
  tasks:
  - name: Install kubectl  
    snap: 
    - name: kubectl
      classic: true
      state: present
      update_cache: yes
    - name: Create directory and set ownership of .kube directory for jenkins user
      file:
        path: /var/lib/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
    - name: Copy the file from localhost to jenkins
      copy:
        src: "./{{ inventory_hostname }}/admin.conf"
        dest: "/var/lib/jenkins/.kube/config"
        mode: "0600"
        owner: jenkins
        group: jenkins